name: CI

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
      - name: Build
        run: go build -o homekit-pc-lock main/*

  publish:
    name: Publish package
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
      - name: Build
        run: go build -o homekit-pc-lock main/*
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: homekit-pc-lock
          asset_name: homekit-pc-lock-linux-amd64
          tag: ${{ github.ref }}
